name: dentsu_quotes
description: "Dentsu Quotes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.11
  get: ^4.6.6
  get_it: ^7.6.7
  flutter_svg: ^2.0.10+1
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.3.1
  syncfusion_flutter_charts: ^25.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#4A2860"
  color_dark: "#4A2860"
  image: "assets/images/logo.png"
  android_12:
    color: "#4A2860"
    color_dark: "#4A2860"
    image: "assets/images/logo.png"
  android: true
  ios: true
  web: false
  fullscreen: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Black.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-ExtraBold.ttf
        - asset: assets/fonts/DMSans-ExtraLight.ttf
        - asset: assets/fonts/DMSans-Light.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-SemiBold.ttf
        - asset: assets/fonts/DMSans-Thin.ttf
